version: 0.2

phases: 
  install: 
    runtime-versions:
      nodejs: 18 
  pre_build:
    command:
      - cd .\myapp\
      - echo Installing source NPM dependencies. . .
      - npm install -g npm@20.10.0
      - npm ci
  build:
    commands:      
      - npm run build
artifacts:
  files:
    - '**/*'
    #- "mytest/build/**/*"
  base-directory: '.\myapp\build'
  #discard-paths: yes